package lab;

/** Respuestas y notas de procedencia visibles dentro de la aplicación. */
final class Lessons {
    private Lessons() {}
    static String intro(App.Module m){return switch(m){
        case GRAFO2->"Transcripción de Grafo2/2.pdf. Inicio 0, meta 9. Compara camino más corto y camino de menor coste.";
        case CLASE->"Transcripción de grafoclase.pdf. Inicio 0, meta 10. A* reabre estados cuando encuentra un g mejor.";
        case DLS_ROMANIA->"Arad → Bucarest, límite 4. Contrasta la poda por estado con la reapertura a menor profundidad.";
        case ASTAR_ROMANIA->"Oradea → Bucarest. A* debe encontrar un camino de coste 429 con la heurística de la hoja.";
        case PING->"Enunciado original: AB primero; A=10, B=15, C=17. Es imposible. Cambiar el primer partido a BC crea una variante resoluble.";
        case ISLANDS->"Transporta lobo, oveja y col. No dejes lobo–oveja u oveja–col solos sin el barquero.";
        case MISSIONARIES->"Tres misioneros y tres caníbales. Bote para 1–2 personas. Mantén seguras las dos orillas.";
        case BINARY->"Estado n; sucesores 2n y 2n+1. Árbol finito 1–15 por defecto, meta 13 y raíz a profundidad 0.";
        case TRAP->"Una heurística deliberadamente mala guía a Greedy por ocho aristas; BFS encuentra la ruta de dos.";
        case COLUMN->"Salta un bloque de bolas del mismo color, distinto del móvil, hasta un hueco. Objetivo: dejar una sola bola.";
        default->"Explora, formula, ejecuta y comprueba.";
    };}
    static String detail(App.Module m){return switch(m){
        case GRAFO2->"<h2>Grafo 2</h2><p><b>Fuente:</b> Tema2/Grafo2.zip, 2.pdf y cinco trazas de referencia. Cada nodo se rotula estado:h. Las aristas son dirigidas y tienen costes.</p><p>UCS y A* encuentran coste <b>16</b>; un camino óptimo es 0 → 5 → 3 → 6 → 9. Existe el empate 0 → 5 → 2 → 6 → 9, también 16. Por eso un camino distinto no demuestra un error.</p><p>Sucesores por identificador ascendente; desempate por orden de inserción. DLS usa límite 7 como la hoja 2__Depth7_.pdf. No se promete igualdad de todos los identificadores internos de aquellas trazas.</p><p>La heurística es inconsistente, por ejemplo h(0)=6 &gt; c(0,5)+h(5)=4. A* no usa un cerrado booleano irreversible. Consulta los valores y aristas exactos en la pestaña Datos.</p>";
        case CLASE->"<h2>Grafo de clase</h2><p><b>Fuente:</b> Tema2/grafoclase.pdf, rotado para su lectura. Inicio azul 0; meta roja 10. Solución de coste <b>23</b>: 0 → 6 → 2 → 9 → 4 → 7 → 10.</p><p>Suma: 4+2+6+7+2+2=23. La conexión 4 → 10 de coste 5 es peor que 4 → 7 → 10, coste 4. BFS minimiza aristas, no necesariamente coste.</p><p>Las h del PDF se refieren a la meta original. Al editar la meta, la aplicación pone h=0 en todos los nodos para no reutilizar una heurística sin justificación. Las posiciones del dibujo son solo un diseño visual, no distancias.</p>";
        case DLS_ROMANIA->"<h2>Por qué falla la poda de DLS</h2><p><b>Fuente:</b> ExampleDLSProblemPruning.pdf. Con el orden Arad → Zerind → Oradea → Sibiu, Sibiu se alcanza primero a profundidad 3. Sus sucesores quedan en el límite 4.</p><p>Más tarde se extrae Sibiu a profundidad 1. Un cerrado booleano lo descarta y pierde la solución. El modo correcto lo <b>reabre</b>, pues ahora dispone de más profundidad restante.</p><p>Resultado correcto: <b>Arad → Sibiu → Fagaras → Bucharest</b>, profundidad 3, coste 450. DLS no garantiza coste mínimo: UCS obtiene 418 por Rimnicu y Pitesti. El modo erróneo reproduce el fallo intencionadamente; no certifica que el problema sea imposible.</p><p>En DLS el dato de dominancia es profundidad; en UCS/A* es g. La meta se comprueba antes del corte. IDS reinicia el cerrado en cada iteración.</p>";
        case ASTAR_ROMANIA->"<h2>A* desde Oradea</h2><p><b>Fuente:</b> hw1soln.pdf, apartado 4. Se minimiza f=g+h usando las distancias heurísticas tabuladas hacia Bucarest.</p><p><b>Oradea → Sibiu → Rimnicu → Pitesti → Bucharest</b><br>151+80+97+101=<b>429</b>.</p><p>Extracciones antes de la meta: Oradea (f=380), Sibiu (404), Rimnicu (424), Fagaras (426), Pitesti (428), Bucharest (429). El camino por Fagaras tiene coste 461 y es sustituido por el candidato de coste 429.</p><p>Rimnicu abrevia Rimnicu Vilcea. Costes del mapa académico, no kilometrajes actuales para viajar.</p>";
        case PING->"<h2>El enunciado original es imposible</h2><p><b>Fuente:</b> Pinpong.pdf. El primer partido AB ya cuenta: (A,B,C)=(1,1,0). Estado = pareja actual + los tres contadores; acción = ganador; coste = 1 cambio al siguiente partido.</p><p>Sea x=partidos AB, y=AC, z=BC. x+y=10; x+z=15; y+z=17. Por tanto <b>x=4, y=6, z=11</b>: 21 partidos.</p><p>Una pareja no puede jugar dos partidos consecutivos: el perdedor debe salir. Para separar los 11 BC se necesitan los otros 10 partidos y BC debe ocupar ambos extremos: BC, otro, BC, …, otro, BC. Eso contradice el primer partido AB.</p><p><b>La respuesta correcta no es inventar una secuencia.</b> BFS agota el espacio de contadores permitidos. Seleccionar BC conserva los contadores pero cambia explícitamente el enunciado: la variante sí admite 21 partidos y 20 transiciones. En general, suma par y contadores no superiores a la mitad son necesarios, pero no suficientes con una pareja inicial fija.</p>";
        case ISLANDS->"<h2>Lobo, oveja y col</h2><p><b>Fuente:</b> espacioestadoIslas.pdf. Estado: cuatro bits indican la orilla de L, O, C y barquero B; inicio 0000, meta 1111. El barquero cruza solo o con un objeto situado en su orilla.</p><p>Estado seguro: no hay L y O juntos sin B, ni O y C juntos sin B. De las 16 asignaciones, 10 son seguras y alcanzables. BFS encuentra <b>7 cruces</b>.</p><p>Una solución: oveja a B; regreso solo; lobo a B; oveja a A; col a B; regreso solo; oveja a B.</p><p><b>Corrección del dibujo:</b> la salida inicial del barquero solo deja L,O,C sin vigilancia y no es una transición legal del problema clásico. El dibujo incluye esa transición y otra análoga tras la meta; el simulador las filtra.</p>";
        case MISSIONARIES->"<h2>Misioneros y caníbales — hw1, 1(a–e)</h2><p>Estado (M_A,C_A,bote). Inicio (3,3,A), meta (0,0,B). El bote transporta una de las cargas (1,0), (0,1), (2,0), (1,1), (0,2); nunca va vacío.</p><p>En cada orilla M=0 o M≥C; cantidades entre 0 y 3. Los sucesores se filtran por estas condiciones y por la disponibilidad de pasajeros. Coste unitario por cruce.</p><p>BFS encuentra <b>11 cruces</b>. Una exploración exhaustiva que continúa incluso después de la meta tiene <b>16 estados distintos alcanzables</b>. El listado de la hoja repite un estado; el programa utiliza un conjunto y verifica la cardinalidad, no copia la repetición.</p>";
        case BINARY->"<h2>Árbol binario — hw1, 2(a–c)</h2><p>Niveles: 1 / 2,3 / 4,5,6,7 / 8,…,15. Raíz a profundidad 0; la meta 13 está a profundidad 3.</p><p><b>BFS:</b> 1 2 3 4 5 6 7 8 9 10 11 12 13.<br><b>DLS(3):</b> 1 2 4 8 9 5 10 11 3 6 12 13.<br><b>IDS:</b> [1] [1 2 3] [1 2 4 5 3 6 7] [1 2 4 8 9 5 10 11 3 6 12 13].</p><p>Camino: <b>1 → 3 → 6 → 13</b>. La búsqueda inversa es especialmente sencilla: 13 → 6 → 3 → 1, con predecesor floor(n/2) y factor de ramificación 1. La bidireccional es viable, aunque aquí recorrer solo los predecesores resulta más simple.</p><p>El problema matemático tiene infinitos estados. La aplicación muestra y busca en la porción finita parametrizada; no atribuye terminación a DFS sobre el árbol infinito.</p>";
        case TRAP->"<h2>Mala heurística — hw1, apartado 3</h2><p>Grafo de demostración construido para hacer preciso el argumento: S → B → G cuesta 2. La otra ruta S → A1 → … → A7 → G cuesta 8. Todos los costes son 1; h(B)=100, el resto de h=0.</p><p>Greedy visita 9 nodos, incluida la meta, y devuelve 8 pasos. BFS visita 5, incluida la meta, y devuelve 2 pasos con el orden de sucesores fijado. Cuenta de expandidos: 8 y 4, respectivamente. La tabla diferencia expandidos de nodos generados.</p><p><b>Matiz de la hoja:</b> una meta adyacente con h(meta)=0 sería elegida por Greedy. Por eso esta demostración usa una ruta corta de dos aristas en lugar de asignar h positiva a una meta a un salto. La heurística es deliberadamente no admisible; no demuestra un fallo de A* con heurística admisible.</p>";
        case COLUMN->"<h2>Column Jump — hw1, 6(a–h)</h2><p>Estado: matriz n×n, 0=vacío y 1…k=colores. Movimiento: una bola salta horizontal o verticalmente una o más bolas contiguas del mismo color, distinto del suyo, y aterriza en el primer hueco inmediatamente posterior. Se eliminan las bolas saltadas. Coste 1.</p><p>La entrada del PDF tiene 14 bolas. A* encuentra <b>8 saltos</b>. DFS devuelve una solución válida pero puede ser más larga. Se verifican también los ocho movimientos concretos impresos en la hoja.</p><p><b>6(a):</b> con k colores hay (k+1)^(n²) asignaciones. En 7×7 y seis colores: 7^49; excluyendo vacío: 7^49−1; excluyendo también tableros llenos: 7^49−1−6^49. No es un recuento de estados alcanzables desde una instancia.</p><p><b>6(c):</b> dos heurísticas admisibles son h=0 y h=colores_distintos−1. Cada salto elimina bolas de un único color, así que reduce el número de colores distintos a lo sumo en uno. Se usa la segunda. Algunas sugerencias de la hoja, como min(filas_ocupadas,columnas_ocupadas), valen 1 en la meta y no son admisibles sin una reformulación demostrada.</p><p><b>6(d–f):</b> usa DFS, A* y Comparar. Los testExample1/2/3 mencionados en el PDF no están en el repositorio. Sus óptimos declarados son 11/8/9, pero no es posible ejecutar esos tres casos sin sus tableros; no se inventan mediciones. Los tiempos mostrados corresponden solo a la entrada visible.</p><p><b>6(g):</b> IDS encuentra el menor número de saltos con coste unitario si su presupuesto alcanza; repite trabajo y puede ser más lento que DFS. <b>6(h):</b> la búsqueda inversa tiene muchas metas posibles y múltiples formas de reintroducir bolas, por lo que una bidireccional directa no resulta atractiva.</p>";
        default->"<p>Consulta la guía general.</p>";
    };}
    static String guide(){
        StringBuilder b=new StringBuilder("<h1>Resolver no es solo dibujar un camino</h1><p>Laboratorio Java · Temas 1 y 2 · rubences</p><p>Selecciona un ejercicio, revisa su formulación, pulsa <b>Resolver</b> y alterna <b>Camino</b> y <b>Traza</b>. La traza muestra extracciones, cortes, descartes y reaperturas; no es una animación prefabricada. Las búsquedas tienen límites para mantener la aplicación utilizable.</p><h2>Tema 1: percepción → decisión → acción</h2><p>SeguidorLinea.zip contiene dos AVI y 29 imágenes Normal/Error, sin código ni parámetros físicos. La simulación Java es una adaptación 2D explícita, con tres sensores binarios y memoria del último giro. Un agente sin memoria continúa recto al perder la línea; el agente con memoria gira buscando la última detección. Esto mejora algunos casos, pero no garantiza recuperar la pista desde cualquier posición. La galería permite contrastar las imágenes originales sin requerir el simulador grabado.</p><p>Estado interno del modelo: posición, orientación y último giro. Percepción: tres sensores. Acciones: velocidad lineal y giro. Medidas: pasos sin detección y trayectoria. Entorno parcialmente observable para estos sensores; dinámica simulada determinista y continua. No se confunde la posición verdadera, usada para dibujar, con una percepción disponible para el controlador.</p>");
        for(App.Module m:App.Module.values())if(m!=App.Module.LINE&&m!=App.Module.GUIDE)b.append(detail(m));
        b.append("<h2>Equivalencias de búsqueda local — hw1, apartado 5</h2><table><tr><th>Caso</th><th>Equivalencia y condición</th></tr><tr><td>Beam search, k=1</td><td>Hill climbing: conservar el mejor sucesor de un único estado. Bajo el criterio habitual se detiene cuando no mejora; una variante de beam que obliga a moverse debe explicitar esa diferencia.</td></tr><tr><td>Beam: un inicio, sin límite de estados retenidos</td><td>Expansión por niveles como BFS, si conserva todos los sucesores y comprueba metas por nivel; la política de repetidos debe mantenerse coherente.</td></tr><tr><td>Annealing con T→0, sin parada</td><td>Hill climbing de primera elección: vecino aleatorio, aceptar mejoras, rechazar empeoramientos. El tratamiento de empates depende de la implementación; no calcular literalmente exp(Δ/T) con T=0.</td></tr><tr><td>Genético, N=1</td><td>El cruce del único individuo consigo mismo no aporta variación. Con mutación y sustitución incondicional equivale a un paseo aleatorio inducido por la mutación. Con elitismo estricto ya no sería ese mismo paseo.</td></tr></table>");
        b.append("<h2>Cómo interpretar resultados</h2><p>BFS: menor número de acciones, no menor coste ponderado. UCS: menor coste con aristas no negativas en estos grafos finitos. Greedy: no garantiza optimalidad. A*: requiere h admisible y reapertura por g para conservar optimalidad con h inconsistente. DLS: profundidad acotada y dominancia por menor profundidad. IDS: repetición de DLS con límites crecientes.</p><p><b>Solución encontrada</b> incluye un camino que se valida con la función de sucesores. <b>Corte</b> pide aumentar profundidad. <b>Presupuesto agotado</b> no prueba imposibilidad. <b>Espacio finito agotado</b> significa que la búsqueda correcta terminó sin meta. El modo DLS erróneo es una excepción intencional, señalada en rojo.</p><p>La frontera muestra los próximos 16 nodos y el número restante. La traza se acota a 1.200 registros; si se trunca, se anuncia y se conserva la meta final. Los tiempos son observaciones de esta ejecución, no un benchmark estadístico.</p><h2>Procedencia</h2><p>Fuentes primarias: Tema1/SeguidorLinea.zip; Tema2/Grafo2.zip; grafoclase.pdf; ExampleDLSProblemPruning.pdf; Pinpong.pdf; espacioestadoIslas.pdf; hw1soln.pdf (15-381, Spring 2007). Originales preservados. Mapa académico de Rumanía: AIMA; no cartografía para navegación. Documentación técnica de Swing: Java SE, javax.swing.SwingWorker.</p>");
        return b.toString();
    }
}
